### PR TITLE
Expose services' addresses

### PR DESCRIPTION
**Pull request by mojiiba**
most gnsi tests require creating additional grpc connections (specially for negative testing) with different usernames and certificates. This is a quick fix to expose service addresses, so tests can dial grpc connection.  will push the code for static bind if u agree with this change.

### CODE REVIEW

**Comment by mojiiba** [comment]
> I'm not sure about this change. I think I know the answer to this, but to start, why can't `RawAPIs().GNSI().New(t)` be used to create those additional grpc connections?

New(t) alwyas use the same config (certificate, user, pass) from the binding file. However, we need to use different config in gnsi testing.  Two simple examples: (1) we need to create a grpc connection with expired certificate and validate if the connection is unsuccessful (2) we need to create a grpc connection for user x and give it access to gnmi. To validate this, we want to validate if the gnmi request by the user x is getting accepted.  There is no way currently to implement these tests easily.

**Comment by greg-dennis** [comment]
@mojiiba, if you could provide additional dial options to `New(t)`, and implement it so that these dial options override the baked-in ones, would that suffice?

**Comment by mojiiba** [comment]
> @mojiiba, if you could provide additional dial options to `New(t)`, and implement it so that these dial options override the baked-in ones, would that suffice?

yes changing New(t) can help. However New is defined for each service and can restrict us for doing all testing scenarios. Examples, testing mtls or gnsi.cert that will be validated at the grpc level. So, If you do not want top expose address, I would suggest to add a new call "NewGRPC(....)" rather than changing existing New() call.

**Comment by mojiiba** [comment]
@greg-dennis  please let me know what do u suggest to do as the next step?

**Comment by greg-dennis** [comment]
@mojiiba Questions:
* What do you mean by "validated at the grpc level"? 
* What would NewGRPC(....) return, if it existed?

**Comment by mojiiba** [comment]
> @mojiiba Questions:
> 
>     * What do you mean by "validated at the grpc level"?
> 
>     * What would NewGRPC(....) return, if it existed?

Sorry for the confusion. NewGRPC(....) will wrap dial DialGRPC. For now I will go with your suggestion and add dial options to New functions. This should address most of the scenarios. Later, I can open another pull based on the remained scenarios if there will be any.

**Comment by mojiiba** [comment]
> > @mojiiba Questions:
> > ```
> > * What do you mean by "validated at the grpc level"?
> > 
> > * What would NewGRPC(....) return, if it existed?
> > ```
> 
> Sorry for the confusion. NewGRPC(....) will wrap dial DialGRPC. For now I will go with your suggestion and add dial options to New functions. This should address most of the scenarios. Later, I can open another pull based on the remained scenarios if there will be any.

**Comment by mojiiba** [comment]
@greg-dennis  opened a new pull based on your suggestion.
https://github.com/openconfig/ondatra/pull/85

**Pull request closed without merging**
